use crate::types::artist;
use std::collections::HashMap;

use super::{genre::Genre, ArtistID};

// We're going to hardcode artist's Chartmetric ID's
static IDS: HashMap<ArtistList, (ArtistID, Genre)> = HashMap::from([
    (ArtistList::_21_savage, (ArtistID(), Genre:: )),
    (ArtistList::_24kgoldn, (ArtistID(), Genre:: )),
    (ArtistList::_2_chainz, (ArtistID(), Genre:: )),
    (ArtistList::_2pac, (ArtistID(), Genre:: )),
    (ArtistList::_50_cent, (ArtistID(), Genre:: )),
    (ArtistList::_5_seconds_of_summer, (ArtistID(), Genre:: )),
    (ArtistList::_6lack, (ArtistID(), Genre:: )),
    (ArtistList::abba, (ArtistID(), Genre:: )),
    (ArtistList::a_boogie_wit_da_hoodie, (ArtistID(), Genre:: )),
    (ArtistList::ac_dc, (ArtistID(), Genre:: )),
    (ArtistList::adele, (ArtistID(), Genre:: )),
    (ArtistList::aitana, (ArtistID(), Genre:: )),
    (ArtistList::akon, (ArtistID(), Genre:: )),
    (ArtistList::alan_walker, (ArtistID(), Genre:: )),
    (ArtistList::alec_benjamin, (ArtistID(), Genre:: )),
    (ArtistList::alejandro_fernandez, (ArtistID(), Genre:: )),
    (ArtistList::alessia_cara, (ArtistID(), Genre:: )),
    (ArtistList::alesso, (ArtistID(), Genre:: )),
    (ArtistList::alicia_keys, (ArtistID(), Genre:: )),
    (ArtistList::alok, (ArtistID(), Genre:: )),
    (ArtistList::anderson_paak, (ArtistID(), Genre:: )),
    (ArtistList::anirudh_ravichander, (ArtistID(), Genre:: )),
    (ArtistList::anitta, (ArtistID(), Genre:: )),
    (ArtistList::anne_marie, (ArtistID(), Genre:: )),
    (ArtistList::anuel_aa, (ArtistID(), Genre:: )),
    (ArtistList::ap_dhillon, (ArtistID(), Genre:: )),
    (ArtistList::arcane, (ArtistID(), Genre:: )),
    (ArtistList::arcangel, (ArtistID(), Genre:: )),
    (ArtistList::arctic_monkeys, (ArtistID(), Genre:: )),
    (ArtistList::ariana_grande, (ArtistID(), Genre:: )),
    (ArtistList::arijit_singh, (ArtistID(), Genre:: )),
    (ArtistList::ar_rahman, (ArtistID(), Genre:: )),
    (ArtistList::asap_rocky, (ArtistID(), Genre:: )),
    (ArtistList::ava_max, (ArtistID(), Genre:: )),
    (ArtistList::aventura, (ArtistID(), Genre:: )),
    (ArtistList::avicii, (ArtistID(), Genre:: )),
    (ArtistList::avril_lavigne, (ArtistID(), Genre:: )),
    (ArtistList::baby_keem, (ArtistID(), Genre:: )),
    (ArtistList::bad_bunny, (ArtistID(), Genre:: )),
    (ArtistList::banda_ms_de_sergio_lizarraga, (ArtistID(), Genre:: )),
    (ArtistList::bastille, (ArtistID(), Genre:: )),
    (ArtistList::bebe_rexha, (ArtistID(), Genre:: )),
    (ArtistList::becky_g, (ArtistID(), Genre:: )),
    (ArtistList::becky_hill, (ArtistID(), Genre:: )),
    (ArtistList::bee_gees, (ArtistID(), Genre:: )),
    (ArtistList::beyonce, (ArtistID(), Genre:: )),
    (ArtistList::bibi_blocksberg, (ArtistID(), Genre:: )),
    (ArtistList::big_sean, (ArtistID(), Genre:: )),
    (ArtistList::billie_eilish, (ArtistID(), Genre:: )),
    (ArtistList::billy_joel, (ArtistID(), Genre:: )),
    (ArtistList::bizarrap, (ArtistID(), Genre:: )),
    (ArtistList::blackbear, (ArtistID(), Genre:: )),
    (ArtistList::black_eyed_peas, (ArtistID(), Genre:: )),
    (ArtistList::blackpink, (ArtistID(), Genre:: )),
    (ArtistList::blessd, (ArtistID(), Genre:: )),
    (ArtistList::blink_182, (ArtistID(), Genre:: )),
    (ArtistList::bob_marley, (ArtistID(), Genre:: )),
    (ArtistList::bon_jovi, (ArtistID(), Genre:: )),
    (ArtistList::brent_faiyaz, (ArtistID(), Genre:: )),
    (ArtistList::bring_me_the_horizon, (ArtistID(), Genre:: )),
    (ArtistList::britney_spears, (ArtistID(), Genre:: )),
    (ArtistList::bruno_mars, (ArtistID(), Genre:: )),
    (ArtistList::bryant_nevers, (ArtistID(), Genre:: )),
    (ArtistList::bryson_tiller, (ArtistID(), Genre:: )),
    (ArtistList::bts, (ArtistID(), Genre:: )),
    (ArtistList::calibre, (ArtistID(), Genre:: )),
    (ArtistList::calum_scott, (ArtistID(), Genre:: )),
    (ArtistList::calvin_harris, (ArtistID(), Genre:: )),
    (ArtistList::camila_cabello, (ArtistID(), Genre:: )),
    (ArtistList::camilo, (ArtistID(), Genre:: )),
    (ArtistList::cardi_b, (ArtistID(), Genre:: )),
    (ArtistList::carin_leon, (ArtistID(), Genre:: )),
    (ArtistList::carlos_vives, (ArtistID(), Genre:: )),
    (ArtistList::cartel_de_santa, (ArtistID(), Genre:: )),
    (ArtistList::central_cee, (ArtistID(), Genre:: )),
    (ArtistList::chance_the_rapper, (ArtistID(), Genre:: )),
    (ArtistList::charlie_puth, (ArtistID(), Genre:: )),
    (ArtistList::charlixcx, (ArtistID(), Genre:: )),
    (ArtistList::chase_atlantic, (ArtistID(), Genre:: )),
    (ArtistList::chencho_corleone, (ArtistID(), Genre:: )),
    (ArtistList::childish_gambino, (ArtistID(), Genre:: )),
    (ArtistList::chris_brown, (ArtistID(), Genre:: )),
    (ArtistList::christian_nodal, (ArtistID(), Genre:: )),
    (ArtistList::christina_aguilera, (ArtistID(), Genre:: )),
    (ArtistList::cigarettes_after_sex, (ArtistID(), Genre:: )),
    (ArtistList::ckay, (ArtistID(), Genre:: )),
    (ArtistList::clairo, (ArtistID(), Genre:: )),
    (ArtistList::clean_bandit, (ArtistID(), Genre:: )),
    (ArtistList::coldplay, (ArtistID(), Genre:: )),
    (ArtistList::conan_gray, (ArtistID(), Genre:: )),
    (ArtistList::creedence_cleerwater, (ArtistID(), Genre:: )),
    (ArtistList::cris_mj, (ArtistID(), Genre:: )),
    (ArtistList::c_tanaga, (ArtistID(), Genre:: )),
    (ArtistList::dababy, (ArtistID(), Genre:: )),
    (ArtistList::daddy_yankee, (ArtistID(), Genre:: )),
    (ArtistList::daft_punk, (ArtistID(), Genre:: )),
    (ArtistList::dalex, (ArtistID(), Genre:: )),
    (ArtistList::daniel_caesar, (ArtistID(), Genre:: )),
    (ArtistList::danny_ocean, (ArtistID(), Genre:: )),
    (ArtistList::dave, (ArtistID(), Genre:: )),
    (ArtistList::david_bowie, (ArtistID(), Genre:: )),
    (ArtistList::david_guetta, (ArtistID(), Genre:: )),
    (ArtistList::de_la_ghetto, (ArtistID(), Genre:: )),
    (ArtistList::demi_lovato, (ArtistID(), Genre:: )),
    (ArtistList::diane_guerrero, (ArtistID(), Genre:: )),
    (ArtistList::diplo, (ArtistID(), Genre:: )),
    (ArtistList::disney, (ArtistID(), Genre:: )),
    (ArtistList::dj_khaled, (ArtistID(), Genre:: )),
    (ArtistList::dj_snake, (ArtistID(), Genre:: )),
    (ArtistList::doja_cat, (ArtistID(), Genre:: )),
    (ArtistList::dominic_fike, (ArtistID(), Genre:: )),
    (ArtistList::don_omar, (ArtistID(), Genre:: )),
    (ArtistList::don_toliver, (ArtistID(), Genre:: )),
    (ArtistList::dove_cameron, (ArtistID(), Genre:: )),
    (ArtistList::drake, (ArtistID(), Genre:: )),
    (ArtistList::dr_dre, (ArtistID(), Genre:: )),
    (ArtistList::dua_lipa, (ArtistID(), Genre:: )),
    (ArtistList::duki, (ArtistID(), Genre:: )),
    (ArtistList::ed_sheeran, (ArtistID(), Genre:: )),
    (ArtistList::eladio_carrion, (ArtistID(), Genre:: )),
    (ArtistList::el_alfa, (ArtistID(), Genre:: )),
    (ArtistList::elley_duhe, (ArtistID(), Genre:: )),
    (ArtistList::ellie_goulding, (ArtistID(), Genre:: )),
    (ArtistList::elton_john, (ArtistID(), Genre:: )),
    (ArtistList::eminem, (ArtistID(), Genre:: )),
    (ArtistList::encanto_cast, (ArtistID(), Genre:: )),
    (ArtistList::enhypen, (ArtistID(), Genre:: )),
    (ArtistList::enrique_iglesias, (ArtistID(), Genre:: )),
    (ArtistList::fall_out_boy, (ArtistID(), Genre:: )),
    (ArtistList::farruko, (ArtistID(), Genre:: )),
    (ArtistList::feid, (ArtistID(), Genre:: )),
    (ArtistList::fleetwood_mac, (ArtistID(), Genre:: )),
    (ArtistList::flo_rida, (ArtistID(), Genre:: )),
    (ArtistList::foo_fighters, (ArtistID(), Genre:: )),
    (ArtistList::frank_ocean, (ArtistID(), Genre:: )),
    (ArtistList::french_montana, (ArtistID(), Genre:: )),
    (ArtistList::future, (ArtistID(), Genre:: )),
    (ArtistList::galantis, (ArtistID(), Genre:: )),
    (ArtistList::gayle, (ArtistID(), Genre:: )),
    (ArtistList::g_eazy, (ArtistID(), Genre:: )),
    (ArtistList::gera_mx, (ArtistID(), Genre:: )),
    (ArtistList::girl_in_red, (ArtistID(), Genre:: )),
    (ArtistList::giveon, (ArtistID(), Genre:: )),
    (ArtistList::glass_animals, (ArtistID(), Genre:: )),
    (ArtistList::gorillaz, (ArtistID(), Genre:: )),
    (ArtistList::green_day, (ArtistID(), Genre:: )),
    (ArtistList::grupo_firme, (ArtistID(), Genre:: )),
    (ArtistList::gucci_mane, (ArtistID(), Genre:: )),
    (ArtistList::gunna, (ArtistID(), Genre:: )),
    (ArtistList::guns_n_roses, (ArtistID(), Genre:: )),
    (ArtistList::gurinder_gill, (ArtistID(), Genre:: )),
    (ArtistList::gusttavo_lima, (ArtistID(), Genre:: )),
    (ArtistList::halsey, (ArtistID(), Genre:: )),
    (ArtistList::harry_styles, (ArtistID(), Genre:: )),
    (ArtistList::henrique_and_juliano, (ArtistID(), Genre:: )),
    (ArtistList::her, (ArtistID(), Genre:: )),
    (ArtistList::hozier, (ArtistID(), Genre:: )),
    (ArtistList::iann_dior, (ArtistID(), Genre:: )),
    (ArtistList::imagine_dragons, (ArtistID(), Genre:: )),
    (ArtistList::jack_harlow, (ArtistID(), Genre:: )),
    (ArtistList::james_arthur, (ArtistID(), Genre:: )),
    (ArtistList::jason_derulo, (ArtistID(), Genre:: )),
    (ArtistList::jaymes_young, (ArtistID(), Genre:: )),
    (ArtistList::jay_wheeler, (ArtistID(), Genre:: )),
    (ArtistList::jay_z, (ArtistID(), Genre:: )),
    (ArtistList::j_balvin, (ArtistID(), Genre:: )),
    (ArtistList::j_cole, (ArtistID(), Genre:: )),
    (ArtistList::jennifer_lopez, (ArtistID(), Genre:: )),
    (ArtistList::jeremih, (ArtistID(), Genre:: )),
    (ArtistList::jhay_cortez, (ArtistID(), Genre:: )),
    (ArtistList::jhene_aiko, (ArtistID(), Genre:: )),
    (ArtistList::jid, (ArtistID(), Genre:: )),
    (ArtistList::joel_corry, (ArtistID(), Genre:: )),
    (ArtistList::johann_sebastian_bach, (ArtistID(), Genre:: )),
    (ArtistList::john_legend, (ArtistID(), Genre:: )),
    (ArtistList::john_mayer, (ArtistID(), Genre:: )),
    (ArtistList::joji, (ArtistID(), Genre:: )),
    (ArtistList::jonas_blue, (ArtistID(), Genre:: )),
    (ArtistList::jonas_brothers, (ArtistID(), Genre:: )),
    (ArtistList::jorje_and_mateus, (ArtistID(), Genre:: )),
    (ArtistList::juice_wrld, (ArtistID(), Genre:: )),
    (ArtistList::jul, (ArtistID(), Genre:: )),
    (ArtistList::julia_michaels, (ArtistID(), Genre:: )),
    (ArtistList::julieta_venegas, (ArtistID(), Genre:: )),
    (ArtistList::junior_h, (ArtistID(), Genre:: )),
    (ArtistList::justin_bieber, (ArtistID(), Genre:: )),
    (ArtistList::justin_quiles, (ArtistID(), Genre:: )),
    (ArtistList::justin_timberlake, (ArtistID(), Genre:: )),
    (ArtistList::kali_uchis, (ArtistID(), Genre:: )),
    (ArtistList::kanye_west, (ArtistID(), Genre:: )),
    (ArtistList::karol_g, (ArtistID(), Genre:: )),
    (ArtistList::katy_perry, (ArtistID(), Genre:: )),
    (ArtistList::kehlani, (ArtistID(), Genre:: )),
    (ArtistList::kendrick_lamar, (ArtistID(), Genre:: )),
    (ArtistList::kesha, (ArtistID(), Genre:: )),
    (ArtistList::kevin_gates, (ArtistID(), Genre:: )),
    (ArtistList::khalid, (ArtistID(), Genre:: )),
    (ArtistList::kid_cudi, (ArtistID(), Genre:: )),
    (ArtistList::king_von, (ArtistID(), Genre:: )),
    (ArtistList::kodak_black, (ArtistID(), Genre:: )),
    (ArtistList::kygo, (ArtistID(), Genre:: )),
    (ArtistList::labrinth, (ArtistID(), Genre:: )),
    (ArtistList::lady_gaga, (ArtistID(), Genre:: )),
    (ArtistList::lana_del_rey, (ArtistID(), Genre:: )),
    (ArtistList::lauv, (ArtistID(), Genre:: )),
    (ArtistList::league_of_legends, (ArtistID(), Genre:: )),
    (ArtistList::led_zepplin, (ArtistID(), Genre:: )),
    (ArtistList::lenny_tavarez, (ArtistID(), Genre:: )),
    (ArtistList::lewis_capaldi, (ArtistID(), Genre:: )),
    (ArtistList::lil_baby, (ArtistID(), Genre:: )),
    (ArtistList::lil_durk, (ArtistID(), Genre:: )),
    (ArtistList::lil_nas_x, (ArtistID(), Genre:: )),
    (ArtistList::lil_peep, (ArtistID(), Genre:: )),
    (ArtistList::lil_tecca, (ArtistID(), Genre:: )),
    (ArtistList::lil_tjay, (ArtistID(), Genre:: )),
    (ArtistList::lil_uzi_vert, (ArtistID(), Genre:: )),
    (ArtistList::lil_wayne, (ArtistID(), Genre:: )),
    (ArtistList::lil_yachty, (ArtistID(), Genre:: )),
    (ArtistList::linkin_park, (ArtistID(), Genre:: )),
    (ArtistList::lit_killah, (ArtistID(), Genre:: )),
    (ArtistList::little_mix, (ArtistID(), Genre:: )),
    (ArtistList::logic, (ArtistID(), Genre:: )),
    (ArtistList::lorde, (ArtistID(), Genre:: )),
    (ArtistList::lost_frequencies, (ArtistID(), Genre:: )),
    (ArtistList::ludacris, (ArtistID(), Genre:: )),
    (ArtistList::ludovico_einaudi, (ArtistID(), Genre:: )),
    (ArtistList::luis_fonsi, (ArtistID(), Genre:: )),
    (ArtistList::luis_miguel, (ArtistID(), Genre:: )),
    (ArtistList::luis_r_conriquez, (ArtistID(), Genre:: )),
    (ArtistList::luke_combs, (ArtistID(), Genre:: )),
    (ArtistList::lunay, (ArtistID(), Genre:: )),
    (ArtistList::mac_demarco, (ArtistID(), Genre:: )),
    (ArtistList::machine_gun_kelly, (ArtistID(), Genre:: )),
    (ArtistList::macklemore, (ArtistID(), Genre:: )),
    (ArtistList::mac_miller, (ArtistID(), Genre:: )),
    (ArtistList::madonna, (ArtistID(), Genre:: )),
    (ArtistList::maiara_and_maraisa, (ArtistID(), Genre:: )),
    (ArtistList::mainstreet, (ArtistID(), Genre:: )),
    (ArtistList::maluma, (ArtistID(), Genre:: )),
    (ArtistList::mana, (ArtistID(), Genre:: )),
    (ArtistList::maneskin, (ArtistID(), Genre:: )),
    (ArtistList::manuel_turizo, (ArtistID(), Genre:: )),
    (ArtistList::marc_anthony, (ArtistID(), Genre:: )),
    (ArtistList::maria_becerra, (ArtistID(), Genre:: )),
    (ArtistList::mariah_carey, (ArtistID(), Genre:: )),
    (ArtistList::marilia_mendonca, (ArtistID(), Genre:: )),
    (ArtistList::maroon_5, (ArtistID(), Genre:: )),
    (ArtistList::marshmello, (ArtistID(), Genre:: )),
    (ArtistList::martin_garrix, (ArtistID(), Genre:: )),
    (ArtistList::meek_mill, (ArtistID(), Genre:: )),
    (ArtistList::megan_thee_stallion, (ArtistID(), Genre:: )),
    (ArtistList::meghan_trainor, (ArtistID(), Genre:: )),
    (ArtistList::melanie_martinez, (ArtistID(), Genre:: )),
    (ArtistList::metallica, (ArtistID(), Genre:: )),
    (ArtistList::metro_boomin, (ArtistID(), Genre:: )),
    (ArtistList::michael_jackson, (ArtistID(), Genre:: )),
    (ArtistList::migos, (ArtistID(), Genre:: )),
    (ArtistList::miguel, (ArtistID(), Genre:: )),
    (ArtistList::miley_cyrus, (ArtistID(), Genre:: )),
    (ArtistList::miracle_tones, (ArtistID(), Genre:: )),
    (ArtistList::mitski, (ArtistID(), Genre:: )),
    (ArtistList::moneybagg_yo, (ArtistID(), Genre:: )),
    (ArtistList::mora, (ArtistID(), Genre:: )),
    (ArtistList::morat, (ArtistID(), Genre:: )),
    (ArtistList::morgan_wallen, (ArtistID(), Genre:: )),
    (ArtistList::myke_towers, (ArtistID(), Genre:: )),
    (ArtistList::nate_dogg, (ArtistID(), Genre:: )),
    (ArtistList::natti_natasha, (ArtistID(), Genre:: )),
    (ArtistList::nelly_furtado, (ArtistID(), Genre:: )),
    (ArtistList::nengo_flow, (ArtistID(), Genre:: )),
    (ArtistList::neyo, (ArtistID(), Genre:: )),
    (ArtistList::nf, (ArtistID(), Genre:: )),
    (ArtistList::niall_horan, (ArtistID(), Genre:: )),
    (ArtistList::nicki_minaj, (ArtistID(), Genre:: )),
    (ArtistList::nicki_nicole, (ArtistID(), Genre:: )),
    (ArtistList::nicky_jam, (ArtistID(), Genre:: )),
    (ArtistList::ninho, (ArtistID(), Genre:: )),
    (ArtistList::nio_garcia, (ArtistID(), Genre:: )),
    (ArtistList::nirvana, (ArtistID(), Genre:: )),
    (ArtistList::nle_choppa, (ArtistID(), Genre:: )),
    (ArtistList::offset_boywithuke, (ArtistID(), Genre:: )),
    (ArtistList::olivia_rodrigo, (ArtistID(), Genre:: )),
    (ArtistList::one_direction, (ArtistID(), Genre:: )),
    (ArtistList::onerepublic, (ArtistID(), Genre:: )),
    (ArtistList::ozuna, (ArtistID(), Genre:: )),
    (ArtistList::panic_at_the_disco, (ArtistID(), Genre:: )),
    (ArtistList::paramore, (ArtistID(), Genre:: )),
    (ArtistList::partynextdoor, (ArtistID(), Genre:: )),
    (ArtistList::paulo_londra, (ArtistID(), Genre:: )),
    (ArtistList::pharrell_williams, (ArtistID(), Genre:: )),
    (ArtistList::pink, (ArtistID(), Genre:: )),
    (ArtistList::pink_floyd, (ArtistID(), Genre:: )),
    (ArtistList::pitbull, (ArtistID(), Genre:: )),
    (ArtistList::playboi_carti, (ArtistID(), Genre:: )),
    (ArtistList::pnau, (ArtistID(), Genre:: )),
    (ArtistList::polo_g, (ArtistID(), Genre:: )),
    (ArtistList::pop_smoke, (ArtistID(), Genre:: )),
    (ArtistList::post_malone, (ArtistID(), Genre:: )),
    (ArtistList::prince_royze, (ArtistID(), Genre:: )),
    (ArtistList::pritam, (ArtistID(), Genre:: )),
    (ArtistList::quavo, (ArtistID(), Genre:: )),
    (ArtistList::queen, (ArtistID(), Genre:: )),
    (ArtistList::r3hab, (ArtistID(), Genre:: )),
    (ArtistList::radiohead, (ArtistID(), Genre:: )),
    (ArtistList::rammstein, (ArtistID(), Genre:: )),
    (ArtistList::rauw_alejandro, (ArtistID(), Genre:: )),
    (ArtistList::red_hot_chilli_peppers, (ArtistID(), Genre:: )),
    (ArtistList::reik, (ArtistID(), Genre:: )),
    (ArtistList::rels_b, (ArtistID(), Genre:: )),
    (ArtistList::rex_orange_county, (ArtistID(), Genre:: )),
    (ArtistList::rick_ross, (ArtistID(), Genre:: )),
    (ArtistList::rico_zion_and_lennox, (ArtistID(), Genre:: )),
    (ArtistList::rihanna, (ArtistID(), Genre:: )),
    (ArtistList::robin_schulz, (ArtistID(), Genre:: )),
    (ArtistList::roddy_ricch, (ArtistID(), Genre:: )),
    (ArtistList::rod_wave, (ArtistID(), Genre:: )),
    (ArtistList::romeo_santos, (ArtistID(), Genre:: )),
    (ArtistList::rosalia, (ArtistID(), Genre:: )),
    (ArtistList::russ, (ArtistID(), Genre:: )),
    (ArtistList::ruth_b, (ArtistID(), Genre:: )),
    (ArtistList::ryan_castro, (ArtistID(), Genre:: )),
    (ArtistList::sam_smith, (ArtistID(), Genre:: )),
    (ArtistList::santa_fe_klan, (ArtistID(), Genre:: )),
    (ArtistList::saweetie, (ArtistID(), Genre:: )),
    (ArtistList::sean_paul, (ArtistID(), Genre:: )),
    (ArtistList::sebastian_yatra, (ArtistID(), Genre:: )),
    (ArtistList::sech, (ArtistID(), Genre:: )),
    (ArtistList::selena_gomez, (ArtistID(), Genre:: )),
    (ArtistList::shakira, (ArtistID(), Genre:: )),
    (ArtistList::shawn_mendes, (ArtistID(), Genre:: )),
    (ArtistList::shreya_ghoshal, (ArtistID(), Genre:: )),
    (ArtistList::sia, (ArtistID(), Genre:: )),
    (ArtistList::silk_sonic, (ArtistID(), Genre:: )),
    (ArtistList::ski_mask_the_slump_god, (ArtistID(), Genre:: )),
    (ArtistList::skrillex, (ArtistID(), Genre:: )),
    (ArtistList::sleep_fruits_music, (ArtistID(), Genre:: )),
    (ArtistList::sleepy_hallow, (ArtistID(), Genre:: )),
    (ArtistList::slipknot, (ArtistID(), Genre:: )),
    (ArtistList::snoop_dogg, (ArtistID(), Genre:: )),
    (ArtistList::stephanie_beatriz, (ArtistID(), Genre:: )),
    (ArtistList::steve_lacy, (ArtistID(), Genre:: )),
    (ArtistList::stray_kids, (ArtistID(), Genre:: )),
    (ArtistList::stromae, (ArtistID(), Genre:: )),
    (ArtistList::suicide_boys, (ArtistID(), Genre:: )),
    (ArtistList::summer_walker, (ArtistID(), Genre:: )),
    (ArtistList::swae_lee, (ArtistID(), Genre:: )),
    (ArtistList::system_of_a_down, (ArtistID(), Genre:: )),
    (ArtistList::sza, (ArtistID(), Genre:: )),
    (ArtistList::tainy, (ArtistID(), Genre:: )),
    (ArtistList::tame_impala, (ArtistID(), Genre:: )),
    (ArtistList::tate_mcrae, (ArtistID(), Genre:: )),
    (ArtistList::taylor_swift, (ArtistID(), Genre:: )),
    (ArtistList::the_beatles, (ArtistID(), Genre:: )),
    (ArtistList::the_chainsmokers, (ArtistID(), Genre:: )),
    (ArtistList::the_kid_laroi, (ArtistID(), Genre:: )),
    (ArtistList::the_killers, (ArtistID(), Genre:: )),
    (ArtistList::the_lumineers, (ArtistID(), Genre:: )),
    (ArtistList::the_neighbourhood, (ArtistID(), Genre:: )),
    (ArtistList::the_notorious_big, (ArtistID(), Genre:: )),
    (ArtistList::the_rolling_stones, (ArtistID(), Genre:: )),
    (ArtistList::the_weeknd, (ArtistID(), Genre:: )),
    (ArtistList::tiago_pzk, (ArtistID(), Genre:: )),
    (ArtistList::tiesto, (ArtistID(), Genre:: )),
    (ArtistList::tini, (ArtistID(), Genre:: )),
    (ArtistList::tomorrow_x_together, (ArtistID(), Genre:: )),
    (ArtistList::tory_lanez, (ArtistID(), Genre:: )),
    (ArtistList::t_pain, (ArtistID(), Genre:: )),
    (ArtistList::travis_scott, (ArtistID(), Genre:: )),
    (ArtistList::trippie_redd, (ArtistID(), Genre:: )),
    (ArtistList::troye_sivan, (ArtistID(), Genre:: )),
    (ArtistList::trueno, (ArtistID(), Genre:: )),
    (ArtistList::tulus, (ArtistID(), Genre:: )),
    (ArtistList::twenty_one_pilots, (ArtistID(), Genre:: )),
    (ArtistList::twice, (ArtistID(), Genre:: )),
    (ArtistList::ty_dolla_sign, (ArtistID(), Genre:: )),
    (ArtistList::tyga, (ArtistID(), Genre:: )),
    (ArtistList::tyler_the_creator, (ArtistID(), Genre:: )),
    (ArtistList::u2, (ArtistID(), Genre:: )),
    (ArtistList::usher, (ArtistID(), Genre:: )),
    (ArtistList::whitney_houston, (ArtistID(), Genre:: )),
    (ArtistList::willow, (ArtistID(), Genre:: )),
    (ArtistList::wisin, (ArtistID(), Genre:: )),
    (ArtistList::wisin_and_yandel, (ArtistID(), Genre:: )),
    (ArtistList::wiz_khalifa, (ArtistID(), Genre:: )),
    (ArtistList::xama, (ArtistID(), Genre:: )),
    (ArtistList::xxxtentacion, (ArtistID(), Genre:: )),
    (ArtistList::yeat, (ArtistID(), Genre:: )),
    (ArtistList::yg, (ArtistID(), Genre:: )),
    (ArtistList::youngboy_never_broke_again, (ArtistID(), Genre:: )),
    (ArtistList::young_thug, (ArtistID(), Genre:: )),
    (ArtistList::zayn, (ArtistID(), Genre:: )),
    (ArtistList::zedd, (ArtistID(), Genre:: )),
    (ArtistList::ze_felipe, (ArtistID(), Genre:: )),
    (ArtistList::zendaya, (ArtistID(), Genre:: )),
    (ArtistList::ze_neto_and_cristiano, (ArtistID(), Genre:: )),
]);

// how do we generate artist ID's?
#[allow(non_camel_case_types)]
pub enum ArtistList {
    // identifiers cannot begin with a number
    _21_savage,
    _24kgoldn,
    _2_chainz,
    _2pac,
    _50_cent,
    _5_seconds_of_summer,
    _6lack,
    abba,
    a_boogie_wit_da_hoodie,
    ac_dc,
    adele,
    aitana,
    akon,
    alan_walker,
    alec_benjamin,
    alejandro_fernandez,
    alessia_cara,
    alesso,
    alicia_keys,
    alok,
    anderson_paak,
    anirudh_ravichander,
    anitta,
    anne_marie,
    anuel_aa,
    ap_dhillon,
    arcane,
    arcangel,
    arctic_monkeys,
    ariana_grande,
    arijit_singh,
    ar_rahman,
    asap_rocky,
    ava_max,
    aventura,
    avicii,
    avril_lavigne,
    baby_keem,
    bad_bunny,
    banda_ms_de_sergio_lizarraga,
    bastille,
    bebe_rexha,
    becky_g,
    becky_hill,
    bee_gees,
    beyonce,
    bibi_blocksberg,
    big_sean,
    billie_eilish,
    billy_joel,
    bizarrap,
    blackbear,
    black_eyed_peas,
    blackpink,
    blessd,
    blink_182,
    bob_marley,
    bon_jovi,
    brent_faiyaz,
    bring_me_the_horizon,
    britney_spears,
    bruno_mars,
    bryant_nevers,
    bryson_tiller,
    bts,
    calibre,
    calum_scott,
    calvin_harris,
    camila_cabello,
    camilo,
    cardi_b,
    carin_leon,
    carlos_vives,
    cartel_de_santa,
    central_cee,
    chance_the_rapper,
    charlie_puth,
    charlixcx,
    chase_atlantic,
    chencho_corleone,
    childish_gambino,
    chris_brown,
    christian_nodal,
    christina_aguilera,
    cigarettes_after_sex,
    ckay,
    clairo,
    clean_bandit,
    coldplay,
    conan_gray,
    creedence_cleerwater,
    cris_mj,
    c_tanaga,
    dababy,
    daddy_yankee,
    daft_punk,
    dalex,
    daniel_caesar,
    danny_ocean,
    dave,
    david_bowie,
    david_guetta,
    de_la_ghetto,
    demi_lovato,
    diane_guerrero,
    diplo,
    disney,
    dj_khaled,
    dj_snake,
    doja_cat,
    dominic_fike,
    don_omar,
    don_toliver,
    dove_cameron,
    drake,
    dr_dre,
    dua_lipa,
    duki,
    ed_sheeran,
    eladio_carrion,
    el_alfa,
    elley_duhe,
    ellie_goulding,
    elton_john,
    eminem,
    encanto_cast,
    enhypen,
    enrique_iglesias,
    fall_out_boy,
    farruko,
    feid,
    fleetwood_mac,
    flo_rida,
    foo_fighters,
    frank_ocean,
    french_montana,
    future,
    galantis,
    gayle,
    g_eazy,
    gera_mx,
    girl_in_red,
    giveon,
    glass_animals,
    gorillaz,
    green_day,
    grupo_firme,
    gucci_mane,
    gunna,
    guns_n_roses,
    gurinder_gill,
    gusttavo_lima,
    halsey,
    harry_styles,
    henrique_and_juliano,
    her,
    hozier,
    iann_dior,
    imagine_dragons,
    jack_harlow,
    james_arthur,
    jason_derulo,
    jaymes_young,
    jay_wheeler,
    jay_z,
    j_balvin,
    j_cole,
    jennifer_lopez,
    jeremih,
    jhay_cortez,
    jhene_aiko,
    jid,
    joel_corry,
    johann_sebastian_bach,
    john_legend,
    john_mayer,
    joji,
    jonas_blue,
    jonas_brothers,
    jorje_and_mateus,
    juice_wrld,
    jul,
    julia_michaels,
    julieta_venegas,
    junior_h,
    justin_bieber,
    justin_quiles,
    justin_timberlake,
    kali_uchis,
    kanye_west,
    karol_g,
    katy_perry,
    kehlani,
    kendrick_lamar,
    kesha,
    kevin_gates,
    khalid,
    kid_cudi,
    king_von,
    kodak_black,
    kygo,
    labrinth,
    lady_gaga,
    lana_del_rey,
    lauv,
    league_of_legends,
    led_zepplin,
    lenny_tavarez,
    lewis_capaldi,
    lil_baby,
    lil_durk,
    lil_nas_x,
    lil_peep,
    lil_tecca,
    lil_tjay,
    lil_uzi_vert,
    lil_wayne,
    lil_yachty,
    linkin_park,
    lit_killah,
    little_mix,
    logic,
    lorde,
    lost_frequencies,
    ludacris,
    ludovico_einaudi,
    luis_fonsi,
    luis_miguel,
    luis_r_conriquez,
    luke_combs,
    lunay,
    mac_demarco,
    machine_gun_kelly,
    macklemore,
    mac_miller,
    madonna,
    maiara_and_maraisa,
    mainstreet,
    maluma,
    mana,
    maneskin,
    manuel_turizo,
    marc_anthony,
    maria_becerra,
    mariah_carey,
    marilia_mendonca,
    maroon_5,
    marshmello,
    martin_garrix,
    meek_mill,
    megan_thee_stallion,
    meghan_trainor,
    melanie_martinez,
    metallica,
    metro_boomin,
    michael_jackson,
    migos,
    miguel,
    miley_cyrus,
    miracle_tones,
    mitski,
    moneybagg_yo,
    mora,
    morat,
    morgan_wallen,
    myke_towers,
    nate_dogg,
    natti_natasha,
    nelly_furtado,
    nengo_flow,
    neyo,
    nf,
    niall_horan,
    nicki_minaj,
    nicki_nicole,
    nicky_jam,
    ninho,
    nio_garcia,
    nirvana,
    nle_choppa,
    offset_boywithuke,
    olivia_rodrigo,
    one_direction,
    onerepublic,
    ozuna,
    panic_at_the_disco,
    paramore,
    partynextdoor,
    paulo_londra,
    pharrell_williams,
    pink,
    pink_floyd,
    pitbull,
    playboi_carti,
    pnau,
    polo_g,
    pop_smoke,
    post_malone,
    prince_royze,
    pritam,
    quavo,
    queen,
    r3hab,
    radiohead,
    rammstein,
    rauw_alejandro,
    red_hot_chilli_peppers,
    reik,
    rels_b,
    rex_orange_county,
    rick_ross,
    rico_zion_and_lennox,
    rihanna,
    robin_schulz,
    roddy_ricch,
    rod_wave,
    romeo_santos,
    rosalia,
    russ,
    ruth_b,
    ryan_castro,
    sam_smith,
    santa_fe_klan,
    saweetie,
    sean_paul,
    sebastian_yatra,
    sech,
    selena_gomez,
    shakira,
    shawn_mendes,
    shreya_ghoshal,
    sia,
    silk_sonic,
    ski_mask_the_slump_god,
    skrillex,
    sleep_fruits_music,
    sleepy_hallow,
    slipknot,
    snoop_dogg,
    stephanie_beatriz,
    steve_lacy,
    stray_kids,
    stromae,
    suicide_boys,
    summer_walker,
    swae_lee,
    system_of_a_down,
    sza,
    tainy,
    tame_impala,
    tate_mcrae,
    taylor_swift,
    the_beatles,
    the_chainsmokers,
    the_kid_laroi,
    the_killers,
    the_lumineers,
    the_neighbourhood,
    the_notorious_big,
    the_rolling_stones,
    the_weeknd,
    tiago_pzk,
    tiesto,
    tini,
    tomorrow_x_together,
    tory_lanez,
    t_pain,
    travis_scott,
    trippie_redd,
    troye_sivan,
    trueno,
    tulus,
    twenty_one_pilots,
    twice,
    ty_dolla_sign,
    tyga,
    tyler_the_creator,
    u2,
    usher,
    whitney_houston,
    willow,
    wisin,
    wisin_and_yandel,
    wiz_khalifa,
    xama,
    xxxtentacion,
    yeat,
    yg,
    youngboy_never_broke_again,
    young_thug,
    zayn,
    zedd,
    ze_felipe,
    zendaya,
    ze_neto_and_cristiano,
}

impl ArtistList {
    pub fn as_str(&self) -> &'static str {
        match self {
            ArtistList::_21_savage => "21 Savage",
            ArtistList::_24kgoldn => "24k Goldn",
            ArtistList::_2_chainz => "2 Chainz",
            ArtistList::_2pac => "Tupac",
            ArtistList::_50_cent => "50 Cent",
            ArtistList::_5_seconds_of_summer => "5 Seconds of Summer",
            ArtistList::_6lack => "6lack",
            ArtistList::abba => "Abba",
            ArtistList::a_boogie_wit_da_hoodie => "A Boogie wit da Hoodie",
            ArtistList::ac_dc => "AC/DC",
            ArtistList::adele => "Adele",
            ArtistList::aitana => "Aitana",
            ArtistList::akon => "Akon",
            ArtistList::alan_walker => "Alan Walker",
            ArtistList::alec_benjamin => "Alec Benjamin",
            ArtistList::alejandro_fernandez => "Alejandro Fernandez",
            ArtistList::alessia_cara => "Alessia Cara",
            ArtistList::alesso => "Alesso",
            ArtistList::alicia_keys => "Alicia Keys",
            ArtistList::alok => "Alok",
            ArtistList::anderson_paak => "Anderson .Paak",
            ArtistList::anirudh_ravichander => "Anirudh Ravichander",
            ArtistList::anitta => "Anitta",
            ArtistList::anne_marie => "Anne Marie",
            ArtistList::anuel_aa => "Anuel AA",
            ArtistList::ap_dhillon => "AP Dhillon",
            ArtistList::arcane => "Arcane",
            ArtistList::arcangel => "Arcangel",
            ArtistList::arctic_monkeys => "Arctic Monkeys",
            ArtistList::ariana_grande => "Ariana Grande",
            ArtistList::arijit_singh => "Arijit Singh",
            ArtistList::ar_rahman => "A.R. Rahman",
            ArtistList::asap_rocky => "A$AP Rocky",
            ArtistList::ava_max => "Ava Max",
            ArtistList::aventura => "Aventura",
            ArtistList::avicii => "Avicii",
            ArtistList::avril_lavigne => "Avril Lavigne",
            ArtistList::baby_keem => "Baby Keem",
            ArtistList::bad_bunny => "Bad Bunny",
            ArtistList::banda_ms_de_sergio_lizarraga => "Banda MS",
            ArtistList::bastille => "Bastille",
            ArtistList::bebe_rexha => "Bebe Rexha",
            ArtistList::becky_g => "Becky G",
            ArtistList::becky_hill => "Becky Hill",
            ArtistList::bee_gees => "Bee Gees",
            ArtistList::beyonce => "Beyonce",
            ArtistList::bibi_blocksberg => "Bibi Blocksberg",
            ArtistList::big_sean => "Big Sean",
            ArtistList::billie_eilish => "Billie Eilish",
            ArtistList::billy_joel => "Billy Joel",
            ArtistList::bizarrap => "Bizarrap",
            ArtistList::blackbear => "Blackbear",
            ArtistList::black_eyed_peas => "Black Eyed Peas",
            ArtistList::blackpink => "Blackpink",
            ArtistList::blessd => "Blessd",
            ArtistList::blink_182 => "Blink 182",
            ArtistList::bob_marley => "Bob Marley",
            ArtistList::bon_jovi => "Bon Jovi",
            ArtistList::brent_faiyaz => "Brent Faiyaz",
            ArtistList::bring_me_the_horizon => "Bring Me the Horizon",
            ArtistList::britney_spears => "Britney Spears",
            ArtistList::bruno_mars => "Bruno Mars",
            ArtistList::bryant_nevers => "Bryant Nevers",
            ArtistList::bryson_tiller => "Bryson Tiller",
            ArtistList::bts => "BTS",
            ArtistList::calibre => "Calibre",
            ArtistList::calum_scott => "Calum Scott",
            ArtistList::calvin_harris => "Calvin Harris",
            ArtistList::camila_cabello => "Camila Cabello",
            ArtistList::camilo => "Camilo",
            ArtistList::cardi_b => "Cardi B",
            ArtistList::carin_leon => "Carin Leon",
            ArtistList::carlos_vives => "Carlos Vives",
            ArtistList::cartel_de_santa => "Cartel de Santa",
            ArtistList::central_cee => "Central Cee",
            ArtistList::chance_the_rapper => "Chance the Rapper",
            ArtistList::charlie_puth => "Charlie Puth",
            ArtistList::charlixcx => "Charli XCX",
            ArtistList::chase_atlantic => "Chase Atlantic",
            ArtistList::chencho_corleone => "Chencho Corleone",
            ArtistList::childish_gambino => "Childish Gambino",
            ArtistList::chris_brown => "Chris Brown",
            ArtistList::christian_nodal => "Christian Nodal",
            ArtistList::christina_aguilera => "Christina Aguilera",
            ArtistList::cigarettes_after_sex => "Cigarettes After Sex",
            ArtistList::ckay => "Ckay",
            ArtistList::clairo => "Clairo",
            ArtistList::clean_bandit => "Clean Bandit",
            ArtistList::coldplay => "Coldplay",
            ArtistList::conan_gray => "Conan Gray",
            ArtistList::creedence_cleerwater => "Creedence Cleerwater",
            ArtistList::cris_mj => "Cris MJ",
            ArtistList::c_tanaga => "C Tanaga",
            ArtistList::dababy => "DaBaby",
            ArtistList::daddy_yankee => "Daddy Yankee",
            ArtistList::daft_punk => "Daft Punk",
            ArtistList::dalex => "Dalex",
            ArtistList::daniel_caesar => "Daniel Caesar",
            ArtistList::danny_ocean => "Danny Ocean",
            ArtistList::dave => "Dave",
            ArtistList::david_bowie => "David Bowie",
            ArtistList::david_guetta => "David Guetta",
            ArtistList::de_la_ghetto => "De La Ghetto",
            ArtistList::demi_lovato => "Demi Lovato",
            ArtistList::diane_guerrero => "Diane Guerrero",
            ArtistList::diplo => "Diplo",
            ArtistList::disney => "Disney",
            ArtistList::dj_khaled => "DJ Khaled",
            ArtistList::dj_snake => "DJ Snake",
            ArtistList::doja_cat => "Doja Cat",
            ArtistList::dominic_fike => "Dominic Fike",
            ArtistList::don_omar => "Don Omar",
            ArtistList::don_toliver => "Don Toliver",
            ArtistList::dove_cameron => "Dove Cameron",
            ArtistList::drake => "Drake",
            ArtistList::dr_dre => "Dr. Dre",
            ArtistList::dua_lipa => "Dua Lipa",
            ArtistList::duki => "Duki",
            ArtistList::ed_sheeran => "Ed Sheeran",
            ArtistList::eladio_carrion => "Eladio Carrion",
            ArtistList::el_alfa => "El Alfa",
            ArtistList::elley_duhe => "Elley Duhe",
            ArtistList::ellie_goulding => "Ellie Goulding",
            ArtistList::elton_john => "Elton John",
            ArtistList::eminem => "Eminem",
            ArtistList::encanto_cast => "Encanto Cast",
            ArtistList::enhypen => "Enhyphen",
            ArtistList::enrique_iglesias => "Enrique Iglesias",
            ArtistList::fall_out_boy => "Fall Out Boy",
            ArtistList::farruko => "Farruko",
            ArtistList::feid => "Feid",
            ArtistList::fleetwood_mac => "Fleetwood Mac",
            ArtistList::flo_rida => "Flo Rida",
            ArtistList::foo_fighters => "Foo Fighters",
            ArtistList::frank_ocean => "Frank Ocean",
            ArtistList::french_montana => "French Montana",
            ArtistList::future => "Future",
            ArtistList::galantis => "Galantis",
            ArtistList::gayle => "Gayle",
            ArtistList::g_eazy => "G-Eazy",
            ArtistList::gera_mx => "Gera MX",
            ArtistList::girl_in_red => "Girl In Red",
            ArtistList::giveon => "Giveon",
            ArtistList::glass_animals => "Glass Animals",
            ArtistList::gorillaz => "Gorillaz",
            ArtistList::green_day => "Green_day",
            ArtistList::grupo_firme => "Grupo Firme",
            ArtistList::gucci_mane => "Gucci Mane",
            ArtistList::gunna => "Gunna",
            ArtistList::guns_n_roses => "Guns n Roses",
            ArtistList::gurinder_gill => "Gurinder Gill",
            ArtistList::gusttavo_lima => "Gusttavo Lima",
            ArtistList::halsey => "Halsey",
            ArtistList::harry_styles => "Harry Styles",
            ArtistList::henrique_and_juliano => "Henrique and Juliano",
            ArtistList::her => "H.E.R.",
            ArtistList::hozier => "Hozier",
            ArtistList::iann_dior => "Iann Dior",
            ArtistList::imagine_dragons => "Imagine Dragons",
            ArtistList::jack_harlow => "Jack Harlow",
            ArtistList::james_arthur => "James Arthur",
            ArtistList::jason_derulo => "Jason Derulo",
            ArtistList::jaymes_young => "Jaymes Young",
            ArtistList::jay_wheeler => "Jay Wheeler",
            ArtistList::jay_z => "Jay-Z",
            ArtistList::j_balvin => "J Balvin",
            ArtistList::j_cole => "J Cole",
            ArtistList::jennifer_lopez => "Jennifer Lopez",
            ArtistList::jeremih => "Jeremih",
            ArtistList::jhay_cortez => "Jhay Cortez",
            ArtistList::jhene_aiko => "Jhene Aiko",
            ArtistList::jid => "JID",
            ArtistList::joel_corry => "Joel Corry",
            ArtistList::johann_sebastian_bach => "Johann Sebastian Bach",
            ArtistList::john_legend => "John Legend",
            ArtistList::john_mayer => "John Mayer",
            ArtistList::joji => "Joji",
            ArtistList::jonas_blue => "Jonas Blue",
            ArtistList::jonas_brothers => "Jonas Brothers",
            ArtistList::jorje_and_mateus => "Jorje and Mateus",
            ArtistList::juice_wrld => "Juice Wrld",
            ArtistList::jul => "Jul",
            ArtistList::julia_michaels => "Julia Michaels",
            ArtistList::julieta_venegas => "Julietta Venegas",
            ArtistList::junior_h => "Junior H",
            ArtistList::justin_bieber => "Justin Bieber",
            ArtistList::justin_quiles => "Justin Quiles",
            ArtistList::justin_timberlake => "Justin Timberlake",
            ArtistList::kali_uchis => "Kali Uchis",
            ArtistList::kanye_west => "Kanye West",
            ArtistList::karol_g => "Karol G",
            ArtistList::katy_perry => "Katy Perry",
            ArtistList::kehlani => "Kehlani",
            ArtistList::kendrick_lamar => "Kendrick Lamar",
            ArtistList::kesha => "Ke$ha",
            ArtistList::kevin_gates => "Kevin Gates",
            ArtistList::khalid => "Khalid",
            ArtistList::kid_cudi => "Kid Cudi",
            ArtistList::king_von => "King Von",
            ArtistList::kodak_black => "Kodak Black",
            ArtistList::kygo => "Kygo",
            ArtistList::labrinth => "Labrinth",
            ArtistList::lady_gaga => "Lady Gaga",
            ArtistList::lana_del_rey => "Lana del Rey",
            ArtistList::lauv => "Lauv",
            ArtistList::league_of_legends => "League of Legends",
            ArtistList::led_zepplin => "Led Zepplin",
            ArtistList::lenny_tavarez => "Lenny Tavarez",
            ArtistList::lewis_capaldi => "Lewis Capaldi",
            ArtistList::lil_baby => "Lil Baby",
            ArtistList::lil_durk => "Lil Durk",
            ArtistList::lil_nas_x => "Lil Nas X",
            ArtistList::lil_peep => "Lil Peep",
            ArtistList::lil_tecca => "Lil Tecca",
            ArtistList::lil_tjay => "Lil Tjay",
            ArtistList::lil_uzi_vert => "Lil Uzi Vert",
            ArtistList::lil_wayne => "Lil Wayne",
            ArtistList::lil_yachty => "Lil Yachty",
            ArtistList::linkin_park => "Linkin Park",
            ArtistList::lit_killah => "Lit Killah",
            ArtistList::little_mix => "Little Mix",
            ArtistList::logic => "Logic",
            ArtistList::lorde => "Lorde",
            ArtistList::lost_frequencies => "Lost Frequencies",
            ArtistList::ludacris => "Ludacris",
            ArtistList::ludovico_einaudi => "Ludovico Einaudi",
            ArtistList::luis_fonsi => "Luis Fonsi",
            ArtistList::luis_miguel => "Luis Miguel",
            ArtistList::luis_r_conriquez => "Luis R Conriquez",
            ArtistList::luke_combs => "Luke Combs",
            ArtistList::lunay => "Lunay",
            ArtistList::mac_demarco => "Mac DeMarco",
            ArtistList::machine_gun_kelly => "Machine Gun Kelly",
            ArtistList::macklemore => "Macklemore",
            ArtistList::mac_miller => "Mac Miller",
            ArtistList::madonna => "Madonna",
            ArtistList::maiara_and_maraisa => "Maiara and Maraisa",
            ArtistList::mainstreet => "Mainstreet",
            ArtistList::maluma => "Maluma",
            ArtistList::mana => "Mana",
            ArtistList::maneskin => "Maneskin",
            ArtistList::manuel_turizo => "Manuel Turizo",
            ArtistList::marc_anthony => "Marc Anthony",
            ArtistList::maria_becerra => "Maria Becerra",
            ArtistList::mariah_carey => "Mariah Carey",
            ArtistList::marilia_mendonca => "Marilia Mendonca",
            ArtistList::maroon_5 => "Maroon 5",
            ArtistList::marshmello => "Marshmello",
            ArtistList::martin_garrix => "Martin Garrix",
            ArtistList::meek_mill => "Meek Mill",
            ArtistList::megan_thee_stallion => "Megan Thee Stallion",
            ArtistList::meghan_trainor => "Meghan Trainor",
            ArtistList::melanie_martinez => "Melanie Martinez",
            ArtistList::metallica => "Metallica",
            ArtistList::metro_boomin => "Metro Boomin",
            ArtistList::michael_jackson => "Michael Jackson",
            ArtistList::migos => "Migos",
            ArtistList::miguel => "Miguel",
            ArtistList::miley_cyrus => "Miley Cyrus",
            ArtistList::miracle_tones => "Miracle Tones",
            ArtistList::mitski => "Mitski",
            ArtistList::moneybagg_yo => "Moneybagg Yo",
            ArtistList::mora => "Mora",
            ArtistList::morat => "Morat",
            ArtistList::morgan_wallen => "Morgan Wallen",
            ArtistList::myke_towers => "Myke Towers",
            ArtistList::nate_dogg => "Nate Dogg",
            ArtistList::natti_natasha => "Natti Natasha",
            ArtistList::nelly_furtado => "Nelly Furtado",
            ArtistList::nengo_flow => "Nengo Flow",
            ArtistList::neyo => "Neyo",
            ArtistList::nf => "NF",
            ArtistList::niall_horan => "Niall Horan",
            ArtistList::nicki_minaj => "Nicki Minaj",
            ArtistList::nicki_nicole => "Nicki Nicole",
            ArtistList::nicky_jam => "Nicky Jam",
            ArtistList::ninho => "Ninho",
            ArtistList::nio_garcia => "Nio Garcia",
            ArtistList::nirvana => "Nirvana",
            ArtistList::nle_choppa => "NLE Choppa",
            ArtistList::offset => "Offset",
            ArtistList::boywithuke => "BoyWithUke",
            ArtistList::olivia_rodrigo => "Olivia Rodrigo",
            ArtistList::one_direction => "One Direction",
            ArtistList::onerepublic => "OneRepublic",
            ArtistList::ozuna => "Ozuna",
            ArtistList::panic_at_the_disco => "Panic at the Disco",
            ArtistList::paramore => "Paramore",
            ArtistList::partynextdoor => "PartyNextDoor",
            ArtistList::paulo_londra => "Paulo Londra",
            ArtistList::pharrell_williams => "Pharell Williams",
            ArtistList::pink => "Pink",
            ArtistList::pink_floyd => "Pink Floyd",
            ArtistList::pitbull => "Pitbull",
            ArtistList::playboi_carti => "Playboi Carti",
            ArtistList::pnau => "Pnau",
            ArtistList::polo_g => "Polo G",
            ArtistList::pop_smoke => "Pop Smoke",
            ArtistList::post_malone => "Post Malone",
            ArtistList::prince_royze => "Prince Royze",
            ArtistList::pritam => "Pritam",
            ArtistList::quavo => "Quavo",
            ArtistList::queen => "Queen",
            ArtistList::r3hab => "R3hab",
            ArtistList::radiohead => "Radiohead",
            ArtistList::rammstein => "Rammstein",
            ArtistList::rauw_alejandro => "Rauw Alejandro",
            ArtistList::red_hot_chilli_peppers => "Red Hot Chilli Peppers",
            ArtistList::reik => "Reik",
            ArtistList::rels_b => "Rels B",
            ArtistList::rex_orange_county => "Rex Orange County",
            ArtistList::rick_ross => "Rick Ross",
            ArtistList::rico_zion_and_lennox => "Rico Zion and Lennox",
            ArtistList::rihanna => "Rihanna",
            ArtistList::robin_schulz => "Robin Schulz",
            ArtistList::roddy_ricch => "Roddy Ricch",
            ArtistList::rod_wave => "Rod Wave",
            ArtistList::romeo_santos => "Romeo Santos",
            ArtistList::rosalia => "Rosalia",
            ArtistList::russ => "Russ",
            ArtistList::ruth_b => "Ruth B",
            ArtistList::ryan_castro => "Ryan Castro",
            ArtistList::sam_smith => "Sam Smith",
            ArtistList::santa_fe_klan => "Santa Fe Klan",
            ArtistList::saweetie => "Saweetie",
            ArtistList::sean_paul => "Sean Paul",
            ArtistList::sebastian_yatra => "Sebastian Yatra",
            ArtistList::sech => "Sech",
            ArtistList::selena_gomez => "Selena Gomez",
            ArtistList::shakira => "Shakira",
            ArtistList::shawn_mendes => "Shawn Mendes",
            ArtistList::shreya_ghoshal => "Shreya Ghoshal",
            ArtistList::sia => "Sia",
            ArtistList::silk_sonic => "Silk Sonic",
            ArtistList::ski_mask_the_slump_god => "Ski Mask the Slump God",
            ArtistList::skrillex => "Skrillex",
            ArtistList::sleep_fruits_music => "Sleep Fruits Music",
            ArtistList::sleepy_hallow => "Sleepy Hallow",
            ArtistList::slipknot => "Slipknow",
            ArtistList::snoop_dogg => "Snoop Dogg",
            ArtistList::stephanie_beatriz => "Stephanie Beatriz",
            ArtistList::steve_lacy => "Steve Lacy",
            ArtistList::stray_kids => "Stray Kids",
            ArtistList::stromae => "Stromae",
            ArtistList::suicide_boys => "Suicide Boys",
            ArtistList::summer_walker => "Summer Walker",
            ArtistList::swae_lee => "Swae Lee",
            ArtistList::system_of_a_down => "System of a Down",
            ArtistList::sza => "SZA",
            ArtistList::tainy => "Tainy",
            ArtistList::tame_impala => "Tame Impala",
            ArtistList::tate_mcrae => "Tate Mcrae",
            ArtistList::taylor_swift => "Taylor Swift",
            ArtistList::the_beatles => "The Beatles",
            ArtistList::the_chainsmokers => "The Chainsmokers",
            ArtistList::the_kid_laroi => "The Kid Laroi",
            ArtistList::the_killers => "The Killers",
            ArtistList::the_lumineers => "The Lumineers",
            ArtistList::the_neighbourhood => "The Neighbourhood",
            ArtistList::the_notorious_big => "The Notorious BIG",
            ArtistList::the_rolling_stones => "The Rolling Stones",
            ArtistList::the_weeknd => "The Weeknd",
            ArtistList::tiago_pzk => "Tiago PZK",
            ArtistList::tiesto => "Tiesto",
            ArtistList::tini => "Tini",
            ArtistList::tomorrow_x_together => "Tomorrow X Together",
            ArtistList::tory_lanez => "Tory Lanez",
            ArtistList::t_pain => "T Pain",
            ArtistList::travis_scott => "Travis Scott",
            ArtistList::trippie_redd => "Trippie Redd",
            ArtistList::troye_sivan => "Troye Sivan",
            ArtistList::trueno => "Trueno",
            ArtistList::tulus => "Tulus",
            ArtistList::twenty_one_pilots => "Twenty One Pilots",
            ArtistList::twice => "Twice",
            ArtistList::ty_dolla_sign => "Ty Dolla Sign",
            ArtistList::tyga => "Tyga",
            ArtistList::tyler_the_creator => "Tyler, the Creator",
            ArtistList::u2 => "U2",
            ArtistList::usher => "Usher",
            ArtistList::whitney_houston => "Whitney Houston",
            ArtistList::willow => "Willow",
            ArtistList::wisin => "Wisin",
            ArtistList::wisin_and_yandel => "Wisin and Yandel",
            ArtistList::wiz_khalifa => "Wiz Khalifa",
            ArtistList::xama => "Xama",
            ArtistList::xxxtentacion => "XXXTentacion",
            ArtistList::yeat => "Yeat",
            ArtistList::yg => "YG",
            ArtistList::youngboy_never_broke_again => "Youngboy Never Broke Again",
            ArtistList::young_thug => "Young Thug",
            ArtistList::zayn => "Zayn",
            ArtistList::zedd => "Zedd",
            ArtistList::ze_felipe => "Ze Felipe",
            ArtistList::ze_neto_and_cristiano => "Ze Neto and Cristiano",
        }
    }
}
